# Generated by Django 4.1.7 on 2023-10-29 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0009_shipmentdetails_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentdetails',
            name='last_name',
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='p_address',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='shipmentdetails',
            name='phone_no',
            field=models.CharField(default='', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
    ]
