# Generated by Django 4.1.7 on 2023-11-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0009_shipmentdetails_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetails',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
