# Generated by Django 4.1.7 on 2023-10-29 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0010_remove_shipmentdetails_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmentdetails',
            old_name='phone_no',
            new_name='phone',
        ),
    ]
