# Generated by Django 4.1.7 on 2023-10-29 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0012_alter_shipmentdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetails',
            name='phone',
            field=models.CharField(default=None, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{8,15}$')]),
        ),
    ]
