# Generated by Django 4.1.7 on 2023-10-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0013_alter_shipmentdetails_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentdetails',
            name='phone',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
