# Generated by Django 4.1.7 on 2023-10-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0014_alter_shipmentdetails_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentdetails',
            name='phone',
        ),
    ]
