# Generated by Django 4.1.7 on 2023-10-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0016_shipmentdetails_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentdetails',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
