# Generated by Django 4.1.7 on 2023-10-29 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_details', '0018_remove_shipmentdetails_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentdetails',
            name='phone',
        ),
    ]
